# # File: .github/workflows/ci.yml

# name: CI - Frontend & User Learning Service

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name:  Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Java 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - name: Set up Node.js 18
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name:  Build & Test Backend (user-learning-service)
#         run: |
#           cd backend/user-learning-service
#           ./mvnw clean install

#       - name:  Build & Test Backend (evaluation-analytics-service)
#         run: |
#           cd backend/evaluation-analytics-service
#           ./mvnw clean install

#       - name:  Build Frontend
#         run: |
#           cd frontend
#           npm install
#           NODE_ENV=development CI='' npm run build

#       - name: Install Playwright Browsers
#         run: |
#           cd e2e
#           npx playwright install --with-deps

#       - name: Run E2E Tests
#         run: |
#           cd e2e
#           npm install
#           NODE_ENV=development npx playwright test

#       - name: Upload Playwright Report on Failure
#         if: failure()
#         uses: actions/upload-artifact@v3
#         with:
#           name: playwright-report
#           path: e2e/playwright-report
# File: .github/workflows/ci.yml

name: CI - Frontend & User Learning Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build & Test Backend (user-learning-service)
        run: |
          cd backend/user-learning-service
          ./mvnw clean install

      - name: Build & Test Backend (evaluation-analytics-service)
        run: |
          cd backend/evaluation-analytics-service
          ./mvnw clean install

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          NODE_ENV=development CI='' npm run build

      - name: Start Backend Services
        run: |
          cd backend/user-learning-service
          ./mvnw spring-boot:run &
          cd ../../backend/evaluation-analytics-service
          ./mvnw spring-boot:run &

      - name: Serve Frontend
        run: |
          npm install -g serve
          serve -s frontend/build -l 3000 &
          
      - name: Wait for All Services to be Ready
        run: |
          npx wait-on http://localhost:3000 \
                      http://localhost:8081/api/health \
                      http://localhost:8082/api/health


      - name: Install Playwright Browsers
        run: |
          cd e2e
          npx playwright install --with-deps

      - name: Run E2E Tests
        run: |
          cd e2e
          npm install
          NODE_ENV=development npx playwright test

      - name: Upload Playwright Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report
